### ISSUE TITLE
Unable to Create SSL Certificate on Windows - No bash installed

### ISSUE THREAD

**Issue by ChrisRidl** [clarkio/secure-node-server#3]
Specs:
* Windows 11
* WSL not installed
* Bash not installed
* Node version: 16.14.0

Steps to reproduce:
1. Clone repo
2. cd into `secure-node-server`
3. npm install
4. `Generate a self-signed certificate using the script found in certificate/create-dev-certificate`  Unable to run this bash command.
5.  I tried opening the `create-dev-certificate` file and running the first line `openssl genrsa -out key.pem` manually and that creates a key.pem file with a private key, but fails with ```WARNING: can't open config file: /etc/ssl/openssl.cnf
Unable to load config info from /etc/ssl/openssl.cnf``` and I cannot complete the 2nd step.

**Comment by ChrisRidl** [comment]
@clarkio - Per stream discussion on Friday, I verified that not having bash installed creates an issue with creating certs. 🙂

**Comment by clarkio** [comment]
Thanks so much for testing this out on Windows. I'll look into what the proper steps are for it and add to the README

**Comment by clarkio** [comment]
Closing as this should be fixed now in PR #5
